# Configuração do Dependabot para atualizações automáticas de dependências
version: 2

updates:
  # Dependências Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "igor"  # Substitua pelo seu username do GitHub
    assignees:
      - "igor"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "gradle"
    # Agrupa atualizações menores
    groups:
      androidx:
        patterns:
          - "androidx.*"
      compose:
        patterns:
          - "androidx.compose.*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
      testing:
        patterns:
          - "*test*"
          - "*junit*"
          - "*espresso*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 3
    reviewers:
      - "igor"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
